### ISSUE TITLE
Mailgun API Key leakage

### ISSUE THREAD

**Issue by ypyf** [hulunote/hulunote#1]
https://github.com/hulunote/hulunote/blob/ed2320e1a27fce032125c013616e4bab190b7f50/src/clj/functor_api/service/login.clj#L71

**Comment by chanshunli** [comment]
Thank @ypyf , this key has expired. 😄

**Comment by ypyf** [comment]
> Thank @ypyf , this key has expired. 😄

Well，you should never hardcode an api key.

**Comment by chanshunli** [comment]
ok, thanks for your suggestion🌹 @ypyf
